# Generated by Django 3.2.4 on 2021-10-20 19:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='petstagramuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
